org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = de.shaijana
mod_id = uwmatica
mod_name = UWmatica
author = shaijana
mod_file_name = uwmatica-fabric

# Current mod version
mod_version = 0.7.0

# Required malilib version
malilib_version = 0.29.3

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.2
minecraft_version = 26.2

fabric_loader_version = 0.19.3
mod_menu_version = 20.0.0-beta.3
fabric_api_version = 0.154.0+26.2

#iris_version = 1.10.7
#iris_mc_version = 26.2
conditionalmixin_version = 0.6.4
